const DB_KEY = 'alderia-roleplay-v1';
const ADMIN_PASSWORD = 'Adminwin';
const placeholderAvatar = 'data:image/svg+xml;charset=UTF-8,' + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 360"><rect width="300" height="360" fill="#d7c08a"/><circle cx="150" cy="125" r="67" fill="#75452d"/><path d="M72 130c8-88 145-114 169 0-30-24-110-25-169 0Z" fill="#382019"/><path d="M70 340c8-104 61-137 80-137s73 33 80 137" fill="#6d391f"/><circle cx="126" cy="126" r="7" fill="#2b1b17"/><circle cx="175" cy="126" r="7" fill="#2b1b17"/><path d="M125 167q25 16 50 0" fill="none" stroke="#2b1b17" stroke-width="5"/><path d="M20 25h260v310H20z" fill="none" stroke="#b78639" stroke-width="3"/></svg>`);
const questArt = ['linear-gradient(135deg,#263d4a,#bd8c55)', 'linear-gradient(135deg,#452b34,#b65c45)', 'linear-gradient(135deg,#244735,#bca25a)'];
const itemArt = ['linear-gradient(135deg,#51321e,#d6a84e)', 'linear-gradient(135deg,#263e56,#9bb9c4)', 'linear-gradient(135deg,#5c2937,#d28a89)', 'linear-gradient(135deg,#3d4b2a,#d7c675)'];
const cloudConfig = window.SUPABASE_CONFIG || {};
const cloudClient = window.supabase && cloudConfig.url?.startsWith('https://') && !cloudConfig.url.includes('YOUR_') && !cloudConfig.anonKey?.includes('YOUR_')
  ? window.supabase.createClient(cloudConfig.url, cloudConfig.anonKey)
  : null;

const seed = {
  currentMemberId: null,
  members: [],
  pending: [],
  quests: [
    { id: 'q1', title: 'เสียงกระซิบแห่งป่าหมอก', rank: 'B', description: 'ตามหานักสำรวจที่หายไป ณ ชายป่าทางเหนือ ก่อนดวงจันทร์จะลับฟ้า', limit: 4, joined: [], rewardGold: 180, rewardStats: 2, rewardItem: 'เข็มทิศเงินของผู้พิทักษ์', image: questArt[0], status: 'Open' },
    { id: 'q2', title: 'คำสาบานใต้หอคอยแดง', rank: 'A', description: 'คุ้มกันคณะทูตผ่านดินแดนต้องสาป พร้อมนำสารลับกลับคืนสู่อาณาจักร', limit: 3, joined: [], rewardGold: 360, rewardStats: 4, rewardItem: 'ผ้าคลุมตราเหยี่ยว', image: questArt[1], status: 'Open' },
    { id: 'q3', title: 'สมบัติของราชันผู้หลับใหล', rank: 'S', description: 'เปิดผนึกห้องใต้ดินโบราณและค้นหามงกุฎที่ถูกลืมเลือนมานับศตวรรษ', limit: 6, joined: [], rewardGold: 800, rewardStats: 8, rewardItem: 'มงกุฎแห่งรุ่งอรุณ', image: questArt[2], status: 'Open' }
  ],
  logs: [{ type: 'admin', text: 'Admin สร้างกระดานเควสเริ่มต้นของอาณาจักร', time: Date.now() }]
};
let db = loadDb();
let state = { view: db.currentMemberId ? 'profile' : 'landing', authMode: 'login', adminTab: 'overview', logFilter: 'all' };
let pendingAccount = null;
let cloudWrite = Promise.resolve();
let remoteUpdatedAt = '';

function loadDb() {
  try { return { ...seed, ...JSON.parse(localStorage.getItem(DB_KEY) || '{}') }; } catch { return structuredClone(seed); }
}
function saveDb() {
  db.currentMemberId = db.currentMemberId || null;
  localStorage.setItem(DB_KEY, JSON.stringify(db));
  if (cloudClient) {
    const sharedData = { ...db, currentMemberId: null };
    cloudWrite = cloudWrite.then(async () => {
      const { error } = await cloudClient.from('alderia_state').upsert({ id: 'main', data: sharedData, updated_at: new Date().toISOString() });
      if (error) console.error('Could not save shared state:', error.message);
    });
    return cloudWrite;
  }
  return Promise.resolve();
}
async function hydrateFromCloud() {
  if (!cloudClient) return;
  const localSession = db.currentMemberId;
  const { data, error } = await cloudClient.from('alderia_state').select('data,updated_at').eq('id', 'main').maybeSingle();
  if (error) return console.warn('Supabase is not ready:', error.message);
  if (data?.updated_at === remoteUpdatedAt) return;
  remoteUpdatedAt = data?.updated_at || remoteUpdatedAt;
  if (data?.data && Object.keys(data.data).length) {
    db = { ...seed, ...data.data, currentMemberId: localSession };
    localStorage.setItem(DB_KEY, JSON.stringify(db));
    state.view = db.currentMemberId ? 'profile' : 'landing';
    render();
  } else {
    saveDb();
  }
}
function member() { return db.members.find(item => item.id === db.currentMemberId); }
function esc(value = '') { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char])); }
function imageValue(value, fallback = placeholderAvatar) { return value || fallback; }
function now() { return new Date().toLocaleString('th-TH', { dateStyle: 'medium', timeStyle: 'short' }); }
function log(type, text) { db.logs.unshift({ type, text, time: Date.now() }); return saveDb(); }
function toast(text) { const el = document.createElement('div'); el.className = 'toast'; el.textContent = text; document.querySelector('#toastStack').appendChild(el); setTimeout(() => el.remove(), 3200); }
function fileToDataUrl(input, callback) { const file = input.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => callback(reader.result, file.name); reader.readAsDataURL(file); }

function render() {
  document.querySelector('#app').innerHTML = views[state.view] ? views[state.view]() : views.landing();
  document.querySelector('#topbar').style.display = state.view === 'landing' ? 'flex' : 'flex';
  bindView();
}
const views = {
  landing: () => `<section class="hero view"><div class="hero-inner"><div class="eyebrow">The chronicles of a living realm</div><h1>ALDERIA<span>Roleplay Community</span></h1><div class="ornament">✦</div><p class="hero-sub">จงก้าวเข้าสู่อาณาจักรที่ทุกคำสาบานมีความหมาย และทุกการผจญภัยจะถูกจารึกไว้ในตำนาน</p><button class="start-seal" data-action="start">เริ่มต้น</button><p class="hint" style="margin-top:28px">สมาชิกใหม่ต้องสร้างบัญชีด้วยอีเมลและรหัสผ่าน</p></div></section>`,
  auth: () => `<section class="form-view view"><div class="scroll-panel"><div class="panel-head"><div><div class="eyebrow">Alderia account</div><h2>${state.authMode === 'register' ? 'สร้างบัญชีสมาชิก' : 'เข้าสู่บัญชีสมาชิก'}</h2><p>ใช้ชื่อผู้ใช้และรหัสผ่านที่ท่านสร้างขึ้นเอง</p></div></div><form class="form-body" id="authForm"><div class="inline-form"><div class="field"><label for="authUsername">ชื่อผู้ใช้</label><input id="authUsername" name="username" required minlength="3" maxlength="24" autocomplete="username" placeholder="เช่น arin_vale"></div><div class="field"><label for="authPassword">รหัสผ่าน</label><input id="authPassword" name="password" type="password" minlength="6" required autocomplete="new-password" placeholder="อย่างน้อย 6 ตัวอักษร"></div><button class="primary-btn" type="submit">${state.authMode === 'register' ? 'สร้างบัญชี' : 'เข้าสู่ระบบ'}</button><div class="auth-note">${state.authMode === 'register' ? 'ชื่อผู้ใช้ต้องไม่ซ้ำกับสมาชิกคนอื่น' : 'ใช้บัญชีเดิมเพื่อกลับเข้าสู่ตัวละครของท่าน'}</div><button class="ghost-btn" type="button" data-action="toggle-auth">${state.authMode === 'register' ? 'มีบัญชีแล้ว? เข้าสู่ระบบ' : 'ยังไม่มีบัญชี? สร้างบัญชีใหม่'}</button><button class="ghost-btn" type="button" data-action="go-home">กลับหน้าหลัก</button></div></form></div></section>`,
  register: () => `<section class="form-view view"><div class="scroll-panel"><div class="panel-head"><div><div class="eyebrow">New character charter</div><h2>ลงทะเบียนตัวละคร</h2><p>เขียนชื่อของท่านลงในม้วนสัญญาแห่งอัลเดรีย</p></div><span class="status-badge">Open</span></div><form class="form-body" id="registerForm"><div class="form-grid"><div class="field"><label for="firstName">ชื่อ (First Name)</label><input id="firstName" name="firstName" required placeholder="เช่น Arin"></div><div class="field"><label for="lastName">นามสกุล (Last Name)</label><input id="lastName" name="lastName" required placeholder="เช่น Valebrook"></div><div class="field"><label for="age">อายุ (Age)</label><input id="age" name="age" type="number" min="13" max="999" required placeholder="21"></div><div class="field"><label for="gender">เพศ (Gender)</label><select id="gender" name="gender" required><option value="">เลือกเพศ</option><option>ชาย</option><option>หญิง</option><option>ไม่ระบุ</option></select></div><div class="field"><label for="job">ตำแหน่ง / อาชีพ (Class / Job)</label><select id="job" name="job" required><option value="">เลือกคลาส</option><option>นักรบ (Warrior)</option><option>จอมเวท (Mage)</option><option>โจร (Rogue)</option><option>นักบวช (Cleric)</option><option>นักล่า (Ranger)</option></select></div><div class="field"><label for="guild">สังกัด (Guild / Faction)</label><select id="guild" name="guild" required><option value="">เลือกสังกัด</option><option>สภาอรุณรุ่ง</option><option>กองอัศวินเหล็ก</option><option>ผู้เฝ้าป่าจันทรา</option><option>สมาคมพ่อค้า</option><option>อิสระ</option></select></div><div class="field full"><label>รูปภาพตัวละคร (Character Portrait)</label><div class="photo-drop"><img class="photo-preview" id="registerPreview" src="${placeholderAvatar}" alt="ตัวอย่างรูปตัวละคร"><input id="portrait" name="portrait" type="file" accept="image/*"><span class="file-name" id="fileName">เลือกรูปภาพเพื่ออัปโหลด</span></div></div></div><div class="form-actions"><button class="ghost-btn" type="button" data-action="go-home">ยกเลิก</button><button class="primary-btn" type="submit">ประทับตราสมัครตัวละคร</button></div></form></div></section>`,
  pending: () => `<section class="form-view view"><div class="scroll-panel" style="text-align:center"><div class="form-body" style="padding:70px 35px"><div class="eyebrow">Awaiting the council</div><div style="font-size:54px;margin:18px">⌛</div><h2 class="section-title">รอการยืนยันจาก Admin</h2><p class="hero-sub">ใบสมัครของท่านถูกส่งถึงสภาแล้ว เมื่อได้รับอนุมัติ ประตูสู่อาณาจักรจะเปิดออก</p><button class="ghost-btn" data-action="go-home">กลับหน้าหลัก</button><button class="primary-btn" data-action="show-admin-login" style="margin-left:8px">เปิด Admin Gate</button></div></div></section>`,
  profile: () => { const m = member(); if (!m) return views.landing(); return `<section class="dashboard view"><div class="dashboard-top"><div><div class="eyebrow">Adventurer's registry / main hub</div><h1>หอทะเบียนนักผจญภัย</h1></div><div class="user-chip"><img class="avatar round" src="${imageValue(m.image)}" alt=""><span>${esc(m.firstName)} ${esc(m.lastName)}</span></div></div><div class="parchment profile-card"><img class="profile-photo" src="${imageValue(m.image)}" alt="ภาพของ ${esc(m.firstName)}"><div class="profile-meta"><div class="eyebrow">Alderia identity card · No. ${m.id.slice(-4)}</div><h2>${esc(m.firstName)} ${esc(m.lastName)}</h2><span class="status-badge">${esc(m.rank || 'Registered Adventurer')}</span><div class="meta-grid"><div><span>อายุ</span><strong>${esc(m.age)} ปี</strong></div><div><span>เพศ</span><strong>${esc(m.gender)}</strong></div><div><span>ตำแหน่ง</span><strong>${esc(m.job)}</strong></div><div><span>สังกัด</span><strong>${esc(m.guild)}</strong></div><div><span>ทองคำ</span><strong>${m.gold.toLocaleString()} ◈</strong></div><div><span>แต้มพร้อมใช้</span><strong>${m.availablePoints} pts</strong></div></div><p class="hint">สถานะใบอนุญาต: ผ่านการรับรองโดยสภาอัลเดรีย</p></div></div><div class="nav-grid"><button class="nav-card" data-action="view-stats"><span class="icon">⚔</span><strong>Character Stats</strong><small>จัดสรรค่าสถานะของตัวละคร</small></button><button class="nav-card" data-action="view-inventory"><span class="icon">🎒</span><strong>Inventory & Treasury</strong><small>คลังอุปกรณ์และการเงิน</small></button><button class="nav-card" data-action="view-quests"><span class="icon">📜</span><strong>Quest Board</strong><small>ภารกิจที่กำลังรอผู้กล้า</small></button></div>${memberOverview()}</section>`; },
  stats: () => { const m = member(); const stats = [['ATK','ค่าโจมตี','atk'],['MATK','ค่าเวทมนตร์','matk'],['DEF','ค่าป้องกัน','def'],['SPD','ความเร็ว','spd'],['WILL','เจตจำนง','will']]; return `<section class="dashboard view"><div class="dashboard-top"><div><div class="eyebrow">Character development</div><h1>สมุดสเตตัส</h1></div><button class="ghost-btn" data-action="view-profile">← กลับ Profile</button></div><div class="content-grid"><div class="parchment section-block"><h2>คุณลักษณะของตัวละคร</h2><div class="stat-list">${stats.map(([code, label, key]) => `<div class="stat-row"><span class="stat-code">${code}</span><div><span class="stat-label">${label}</span><div class="progress-line"><i style="width:${Math.min(100, m.stats[key] * 4)}%"></i></div></div><strong class="stat-value">${m.stats[key]}</strong><button class="add-stat" data-action="add-stat" data-stat="${key}" title="เพิ่มแต้ม">+</button></div>`).join('')}</div></div><div class="parchment section-block"><h2>แต้มที่เหลือ</h2><div class="wallet-amount"><strong>${m.availablePoints}</strong><span class="coin">POINTS</span></div><p class="hint">ใช้แต้มที่ได้รับจากสภาเพื่อพัฒนาความสามารถ แต้มที่ใช้แล้วไม่สามารถเรียกคืนได้</p><hr class="tiny-divider"><div class="auth-note">ข้อกำหนด: ผู้เล่นสามารถเพิ่มแต้มเท่านั้น การลดแต้มและการพิมพ์ตัวเลขทำได้โดย Admin เท่านั้น</div></div></div></section>`; },
  inventory: () => { const m = member(); return `<section class="dashboard view"><div class="dashboard-top"><div><div class="eyebrow">Personal treasury</div><h1>คลังอุปกรณ์ & การเงิน</h1></div><button class="ghost-btn" data-action="view-profile">← กลับ Profile</button></div><div class="content-grid"><div class="parchment section-block"><h2>กระเป๋าเงิน</h2><div class="wallet-amount"><strong>${m.gold.toLocaleString()}</strong><span class="coin">◈ GOLD</span></div><hr class="tiny-divider"><h2 style="font-size:18px">โอนเงินให้ผู้รับ</h2><form class="inline-form" id="transferForm"><div class="field"><label>ผู้รับ</label><select name="recipient" required><option value="">เลือกสมาชิก / NPC</option>${db.members.filter(x => x.id !== m.id && x.approved).map(x => `<option value="${x.id}">${esc(x.firstName)} ${esc(x.lastName)}</option>`).join('')}<option value="npc:healer">NPC · นักบวชประจำเมือง</option><option value="npc:smith">NPC · ช่างตีเหล็ก</option></select></div><div class="field"><label>จำนวนทอง</label><input name="amount" type="number" min="1" max="${m.gold}" required></div><button class="wood-btn" type="submit">ยืนยันการโอน</button></form></div><div class="parchment section-block"><h2>คลังอุปกรณ์ (${m.inventory.length})</h2>${m.inventory.length ? `<div class="inventory-grid">${m.inventory.map((item, index) => `<button class="item-card" data-action="item-detail" data-index="${index}"><img src="${imageValue(item.image, itemArt[index % itemArt.length])}" alt=""><strong>${esc(item.name)}</strong><small>${esc(item.rarity)}</small></button>`).join('')}</div>` : '<div class="empty">ยังไม่มีอุปกรณ์ในคลัง</div>'}</div></div></section>`; },
  quests: () => `<section class="dashboard view"><div class="dashboard-top"><div><div class="eyebrow">Notices from the realm</div><h1>กระดานเควส</h1></div><button class="ghost-btn" data-action="view-profile">← กลับ Profile</button></div><div class="quest-board"><div class="eyebrow">Public quest board · ${db.quests.filter(q => q.status === 'Open').length} notices</div><h2 class="section-title">ประกาศภารกิจแห่งอัลเดรีย</h2><div class="quest-list">${db.quests.map(q => questCard(q)).join('')}</div></div></section>`,
  admin: () => `<section class="dashboard view"><div class="dashboard-top"><div><div class="eyebrow">Council control room</div><h1>ห้องบัญชาการ Admin</h1></div><button class="ghost-btn" data-action="go-home">ออกจากระบบ</button></div><nav class="admin-nav">${[['overview','♜ Overview'],['stats','✦ Grant Stats'],['assets','◈ Assets & Gold'],['quests','⚑ Quest Management'],['logs','☷ Audit Logs']].map(([key, label]) => `<button class="ghost-btn ${state.adminTab === key ? 'active' : ''}" data-action="admin-tab" data-tab="${key}">${label}</button>`).join('')}</nav>${adminViews[state.adminTab]()}</section>`
};
function memberOverview() { const m = member(); return `<div class="content-grid"><div class="parchment section-block"><h2>บันทึกการเดินทาง</h2><p class="hint">ยินดีต้อนรับ ${esc(m.firstName)} สู่เส้นทางของท่าน ทุกภารกิจที่สำเร็จจะกลายเป็นชื่อเสียง</p><div class="stats-strip"><div class="metric"><strong>${m.stats.atk + m.stats.matk + m.stats.def + m.stats.spd + m.stats.will}</strong><span>Total power</span></div><div class="metric"><strong>${m.completedQuests}</strong><span>Quests cleared</span></div><div class="metric"><strong>${m.inventory.length}</strong><span>Relics held</span></div></div></div><div class="parchment section-block"><h2>ประกาศจากสภา</h2><p class="hint">กระดานเควสมีภารกิจใหม่รอผู้กล้า โปรดตรวจสอบประกาศและรวมทีมให้พร้อม</p><button class="wood-btn" data-action="view-quests">เปิดกระดานเควส →</button></div></div>`; }
function questCard(q) { const m = member(); const joined = q.joined.includes(m?.id); const full = q.joined.length >= q.limit; const disabled = joined || full || q.status !== 'Open'; return `<article class="quest-card"><div class="quest-cover" style="background-image:${q.image}"><span class="quest-rank">Rank ${esc(q.rank)}</span></div><div class="quest-body"><h3>${esc(q.title)}</h3><p>${esc(q.description)}</p><div class="quest-info"><span>ผู้เข้าร่วม ${q.joined.length}/${q.limit}</span><span>รางวัล ${q.rewardGold} ◈</span></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:13px;gap:8px"><small class="hint">${q.status === 'Open' ? `${q.rewardStats} stat · ${esc(q.rewardItem)}` : q.status}</small><button class="wood-btn" data-action="accept-quest" data-id="${q.id}" ${disabled ? 'disabled' : ''}>${joined ? 'In Progress' : full ? 'เต็มแล้ว' : q.status !== 'Open' ? q.status : 'รับภารกิจ'}</button></div></div></article>`; }

const adminViews = {
  overview: () => { const approved = db.members.filter(m => m.approved); return `<div class="stats-strip"><div class="metric"><strong>${approved.length}</strong><span>Approved members</span></div><div class="metric"><strong>${db.pending.length}</strong><span>Pending approvals</span></div><div class="metric"><strong>${db.quests.length}</strong><span>Quest notices</span></div></div><div class="admin-grid"><div class="parchment admin-panel"><h2>Pending Approvals <span class="tag">${db.pending.length}</span></h2><div class="list-stack">${db.pending.length ? db.pending.map(id => pendingRow(id)).join('') : '<div class="empty">ไม่มีใบสมัครรอการตรวจ</div>'}</div></div><div class="parchment admin-panel"><h2>รายชื่อสมาชิกทั้งหมด</h2><div class="list-stack">${approved.length ? approved.map(m => memberRow(m)).join('') : '<div class="empty">ยังไม่มีสมาชิกที่อนุมัติ</div>'}</div></div></div>`; },
  stats: () => `<div class="admin-grid"><div class="parchment admin-panel"><h2>มอบแต้มสเตตัส</h2><form class="inline-form" id="grantStatsForm"><div class="field"><label>สมาชิก</label><select name="memberId" required>${db.members.filter(m => m.approved).map(m => `<option value="${m.id}">${esc(m.firstName)} ${esc(m.lastName)}</option>`).join('')}</select></div><div class="field"><label>จำนวนแต้ม</label><input type="number" name="points" min="1" max="99" required placeholder="5"></div><button class="wood-btn">ยืนยันการแจกแต้ม</button></form></div><div class="parchment admin-panel"><h2>ยอดสเตตัสปัจจุบัน</h2><div class="list-stack">${db.members.filter(m => m.approved).map(m => `<div class="member-row"><img class="avatar round" src="${imageValue(m.image)}"><div class="row-main"><strong>${esc(m.firstName)} ${esc(m.lastName)}</strong><small>${m.availablePoints} points available</small></div></div>`).join('') || '<div class="empty">ยังไม่มีสมาชิก</div>'}</div></div></div>`,
  assets: () => `<div class="admin-grid"><div class="parchment admin-panel"><h2>มอบอุปกรณ์เข้าคลัง</h2><form class="inline-form" id="grantItemForm"><div class="field"><label>สมาชิกผู้รับ</label><select name="memberId" required>${db.members.filter(m => m.approved).map(m => `<option value="${m.id}">${esc(m.firstName)} ${esc(m.lastName)}</option>`).join('')}</select></div><div class="field"><label>ชื่อไอเทม</label><input name="name" required placeholder="ดาบแห่งรุ่งอรุณ"></div><div class="field"><label>ระดับความหายาก</label><select name="rarity"><option>Common</option><option>Rare</option><option>Epic</option><option>Legendary</option></select></div><div class="field"><label>คำอธิบาย</label><textarea name="description" required placeholder="คุณสมบัติของไอเทม"></textarea></div><div class="field"><label>ภาพไอเทม</label><input name="image" type="file" accept="image/*"></div><button class="wood-btn">ส่งเข้าคลัง</button></form></div><div class="parchment admin-panel"><h2>จัดการเงิน</h2><form class="inline-form" id="manageGoldForm"><div class="field"><label>สมาชิก</label><select name="memberId" required>${db.members.filter(m => m.approved).map(m => `<option value="${m.id}">${esc(m.firstName)} ${esc(m.lastName)}</option>`).join('')}</select></div><div class="field"><label>โหมด</label><select name="mode"><option value="add">มอบเงิน (+)</option><option value="remove">ยึดเงิน (-)</option></select></div><div class="field"><label>จำนวน Gold</label><input type="number" name="amount" min="1" required></div><button class="wood-btn">ดำเนินการ</button></form></div></div>`,
  quests: () => `<div class="admin-grid"><div class="parchment admin-panel"><h2>สร้างเควสใหม่</h2><form class="inline-form" id="createQuestForm"><div class="field"><label>ชื่อเควส</label><input name="title" required placeholder="ชื่อประกาศภารกิจ"></div><div class="form-grid"><div class="field"><label>Rank</label><select name="rank"><option>F</option><option>E</option><option>D</option><option>C</option><option>B</option><option>A</option><option>S</option></select></div><div class="field"><label>จำกัดผู้เข้าร่วม</label><input type="number" name="limit" min="1" value="4" required></div></div><div class="field"><label>เนื้อหา</label><textarea name="description" required></textarea></div><div class="form-grid"><div class="field"><label>รางวัล Gold</label><input type="number" name="rewardGold" min="0" value="100"></div><div class="field"><label>รางวัล Stat Points</label><input type="number" name="rewardStats" min="0" value="1"></div></div><div class="field"><label>รางวัลไอเทม</label><input name="rewardItem" placeholder="ถ้าไม่มีให้เว้นว่าง"></div><button class="wood-btn">อัปโหลดเควส</button></form></div><div class="parchment admin-panel"><h2>ตรวจสอบผลเควส</h2><div class="list-stack">${db.quests.flatMap(q => q.joined.map(memberId => questReviewRow(q, memberId))).join('') || '<div class="empty">ยังไม่มีผู้เล่นรับเควส</div>'}</div></div></div>`,
  logs: () => { const logs = db.logs.filter(x => state.logFilter === 'all' || x.type === state.logFilter); return `<div class="parchment section-block"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h2>Audit Logs & Activity History</h2><div class="tabs"><button class="tab ${state.logFilter === 'all' ? 'active' : ''}" data-action="log-filter" data-filter="all">All</button><button class="tab ${state.logFilter === 'member' ? 'active' : ''}" data-action="log-filter" data-filter="member">Member</button><button class="tab ${state.logFilter === 'admin' ? 'active' : ''}" data-action="log-filter" data-filter="admin">Admin</button></div></div><div class="log-list">${logs.map(l => `<div class="log-row ${l.type}"><i class="log-dot"></i><div><strong>${esc(l.text)}</strong><time>${new Date(l.time).toLocaleString('th-TH')}</time></div></div>`).join('') || '<div class="empty">ยังไม่มีบันทึก</div>'}</div></div>`; }
};
function memberRow(m) { return `<div class="member-row"><img class="avatar round" src="${imageValue(m.image)}"><div class="row-main"><strong>${esc(m.firstName)} ${esc(m.lastName)}</strong><small>${esc(m.job)} · ${esc(m.guild)}</small></div><div class="row-actions"><button class="ghost-btn" data-action="admin-member" data-id="${m.id}">ดู</button><button class="danger-btn" data-action="kick" data-id="${m.id}">เตะ</button></div></div>`; }
function pendingRow(id) { const m = db.members.find(x => x.id === id); if (!m) return ''; return `<div class="review-row"><img class="avatar round" src="${imageValue(m.image)}"><div class="row-main"><strong>${esc(m.firstName)} ${esc(m.lastName)}</strong><small>${esc(m.job)} · สมัครเมื่อ ${new Date(m.createdAt).toLocaleDateString('th-TH')}</small></div><div class="row-actions"><button class="wood-btn" data-action="approve" data-id="${m.id}">อนุมัติ</button><button class="danger-btn" data-action="reject" data-id="${m.id}">ปฏิเสธ</button></div></div>`; }
function questReviewRow(q, memberId) { const m = db.members.find(x => x.id === memberId); if (!m) return ''; return `<div class="review-row"><div class="row-main"><strong>${esc(q.title)}</strong><small>${esc(m.firstName)} ${esc(m.lastName)} · ${q.status}</small></div><div class="row-actions">${q.status === 'Open' ? `<button class="wood-btn" data-action="complete-quest" data-qid="${q.id}" data-mid="${m.id}">Complete</button><button class="danger-btn" data-action="fail-quest" data-qid="${q.id}">Fail</button>` : `<span class="tag">${esc(q.status)}</span>`}</div></div>`; }

function bindView() {
  document.querySelectorAll('[data-action]').forEach(btn => btn.addEventListener('click', handleAction));
  document.querySelector('#registerForm')?.addEventListener('submit', submitRegistration);
  document.querySelector('#authForm')?.addEventListener('submit', submitAuth);
  document.querySelector('#transferForm')?.addEventListener('submit', transferGold);
  document.querySelector('#grantStatsForm')?.addEventListener('submit', grantStats);
  document.querySelector('#grantItemForm')?.addEventListener('submit', grantItem);
  document.querySelector('#manageGoldForm')?.addEventListener('submit', manageGold);
  document.querySelector('#createQuestForm')?.addEventListener('submit', createQuest);
  document.querySelector('#portrait')?.addEventListener('change', e => fileToDataUrl(e.target, (url, name) => { document.querySelector('#registerPreview').src = url; document.querySelector('#fileName').textContent = name; }));
}
function handleAction(e) {
  const action = e.currentTarget.dataset.action;
  if (action === 'start') state.view = member() ? (member().approved ? 'profile' : 'pending') : 'auth';
  if (action === 'go-home') { state.view = 'landing'; saveDb(); }
  if (action === 'view-profile') state.view = 'profile';
  if (action === 'view-stats') state.view = 'stats';
  if (action === 'view-inventory') state.view = 'inventory';
  if (action === 'view-quests') state.view = 'quests';
  if (action === 'show-admin-login') openAdminLogin();
  if (action === 'toggle-auth') { state.authMode = state.authMode === 'login' ? 'register' : 'login'; }
  if (action === 'add-stat') addStat(e.currentTarget.dataset.stat);
  if (action === 'accept-quest') acceptQuest(e.currentTarget.dataset.id);
  if (action === 'item-detail') openItem(Number(e.currentTarget.dataset.index));
  if (action === 'admin-tab') { state.adminTab = e.currentTarget.dataset.tab; render(); }
  if (action === 'approve') approve(e.currentTarget.dataset.id);
  if (action === 'reject') reject(e.currentTarget.dataset.id);
  if (action === 'kick') kick(e.currentTarget.dataset.id);
  if (action === 'admin-member') openAdminMember(e.currentTarget.dataset.id);
  if (action === 'log-filter') { state.logFilter = e.currentTarget.dataset.filter; render(); }
  if (action === 'complete-quest') settleQuest(e.currentTarget.dataset.qid, e.currentTarget.dataset.mid, true);
  if (action === 'fail-quest') settleQuest(e.currentTarget.dataset.qid, e.currentTarget.dataset.mid, false);
  if (action === 'close-modal') closeModal();
  render();
}
async function hashPassword(password) { const bytes = new TextEncoder().encode(password); const digest = await crypto.subtle.digest('SHA-256', bytes); return [...new Uint8Array(digest)].map(value => value.toString(16).padStart(2, '0')).join(''); }
async function submitAuth(e) { e.preventDefault(); const data = new FormData(e.target); const username = String(data.get('username')).trim().toLowerCase(); const passwordHash = await hashPassword(data.get('password')); const existing = db.members.find(item => item.accountUsername === username); if (state.authMode === 'login') { if (!existing || existing.passwordHash !== passwordHash) return toast('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'); db.currentMemberId = existing.id; state.view = existing.approved ? 'profile' : 'pending'; saveDb(); render(); return; } if (existing) return toast('ชื่อผู้ใช้นี้ถูกใช้แล้ว'); pendingAccount = { username, passwordHash }; state.view = 'register'; toast('สร้างบัญชีแล้ว กรุณาสร้างตัวละคร'); render(); }
function submitRegistration(e) { e.preventDefault(); const data = new FormData(e.target); const image = document.querySelector('#registerPreview').src; const newMember = { id: `m${Date.now()}`, accountUsername: pendingAccount?.username || '', passwordHash: pendingAccount?.passwordHash || '', firstName: data.get('firstName'), lastName: data.get('lastName'), age: Number(data.get('age')), gender: data.get('gender'), job: data.get('job'), guild: data.get('guild'), image: image === placeholderAvatar ? '' : image, approved: false, createdAt: Date.now(), rank: 'Pending', gold: 0, availablePoints: 0, stats: { atk: 5, matk: 5, def: 5, spd: 5, will: 5 }, inventory: [], completedQuests: 0 }; db.members.push(newMember); db.pending.push(newMember.id); db.currentMemberId = newMember.id; pendingAccount = null; log('member', `${newMember.firstName} ${newMember.lastName} สมัครตัวละครใหม่`); state.view = 'pending'; toast('ส่งใบสมัครถึงสภาแล้ว'); render(); }
function openAdminLogin() { openModal(`<button class="close-modal" data-action="close-modal">×</button><div class="eyebrow">Restricted access</div><h2>Admin Gate</h2><form class="inline-form" id="adminLoginForm"><div class="field"><label for="adminPassword">รหัสผ่าน Admin</label><input id="adminPassword" name="password" type="password" autocomplete="off" required></div><button class="primary-btn">เข้าสู่ห้องบัญชาการ</button></form>`); document.querySelector('#adminLoginForm').addEventListener('submit', e => { e.preventDefault(); if (new FormData(e.target).get('password') === ADMIN_PASSWORD) { closeModal(); state.view = 'admin'; state.adminTab = 'overview'; render(); toast('เข้าสู่ห้องบัญชาการแล้ว'); } else toast('รหัสผ่านไม่ถูกต้อง'); }); }
function approve(id) { const m = db.members.find(x => x.id === id); if (!m) return; m.approved = true; m.rank = 'Novice Adventurer'; db.pending = db.pending.filter(x => x !== id); log('admin', `Admin อนุมัติสมาชิก ${m.firstName} ${m.lastName}`); toast('อนุมัติสมาชิกแล้ว'); render(); }
function reject(id) { const m = db.members.find(x => x.id === id); db.pending = db.pending.filter(x => x !== id); db.members = db.members.filter(x => x.id !== id); log('admin', `Admin ปฏิเสธใบสมัครของ ${m?.firstName || 'unknown'}`); toast('ปฏิเสธและลบใบสมัครแล้ว'); render(); }
function kick(id) { const m = db.members.find(x => x.id === id); if (!m || !confirm(`ต้องการเตะ ${m.firstName} ${m.lastName} ออกจากระบบหรือไม่?`)) return; db.members = db.members.filter(x => x.id !== id); db.pending = db.pending.filter(x => x !== id); log('admin', `Admin เตะสมาชิก ${m.firstName} ${m.lastName}`); toast('นำสมาชิกออกจากระบบแล้ว'); render(); }
function addStat(key) { const m = member(); if (!m || m.availablePoints < 1) return toast('แต้มของท่านไม่เพียงพอ'); m.stats[key] += 1; m.availablePoints -= 1; log('member', `${m.firstName} อัปสเตตัส ${key} +1`); saveDb(); toast(`เพิ่ม ${key.toUpperCase()} สำเร็จ`); render(); }
function acceptQuest(id) { const q = db.quests.find(x => x.id === id); const m = member(); if (!q || !m || q.joined.includes(m.id) || q.joined.length >= q.limit) return; q.joined.push(m.id); log('member', `${m.firstName} กดรับภารกิจ ${q.title}`); toast('รับภารกิจแล้ว สถานะ In Progress'); render(); }
function transferGold(e) { e.preventDefault(); const data = new FormData(e.target); const amount = Number(data.get('amount')); const sender = member(); const recipientId = data.get('recipient'); if (amount > sender.gold) return toast('ทองของท่านไม่เพียงพอ'); sender.gold -= amount; const recipient = db.members.find(x => x.id === recipientId); if (recipient) recipient.gold += amount; log('member', `${sender.firstName} โอน ${amount} Gold ให้ ${recipient ? recipient.firstName : recipientId}`); saveDb(); toast('โอนเงินสำเร็จ'); render(); }
function grantStats(e) { e.preventDefault(); const data = new FormData(e.target); const m = db.members.find(x => x.id === data.get('memberId')); const points = Number(data.get('points')); if (m) { m.availablePoints += points; log('admin', `Admin มอบ ${points} แต้มให้ ${m.firstName} ${m.lastName}`); saveDb(); toast('มอบแต้มเรียบร้อย'); render(); } }
function grantItem(e) { e.preventDefault(); const data = new FormData(e.target); const m = db.members.find(x => x.id === data.get('memberId')); const input = e.target.querySelector('input[type=file]'); const add = image => { m.inventory.push({ name: data.get('name'), rarity: data.get('rarity'), description: data.get('description'), image: image || '' }); log('admin', `Admin มอบไอเทม ${data.get('name')} ให้ ${m.firstName}`); saveDb(); toast('ส่งไอเทมเข้าคลังแล้ว'); render(); }; if (input.files?.length) fileToDataUrl(input, url => add(url)); else add(''); }
function manageGold(e) { e.preventDefault(); const data = new FormData(e.target); const m = db.members.find(x => x.id === data.get('memberId')); const amount = Number(data.get('amount')); const add = data.get('mode') === 'add'; if (m) { m.gold = Math.max(0, m.gold + (add ? amount : -amount)); log('admin', `Admin ${add ? 'มอบ' : 'ยึด'} ${amount} Gold ${add ? 'ให้' : 'จาก'} ${m.firstName}`); saveDb(); toast('อัปเดตยอดเงินแล้ว'); render(); } }
function createQuest(e) { e.preventDefault(); const data = new FormData(e.target); db.quests.unshift({ id: `q${Date.now()}`, title: data.get('title'), rank: data.get('rank'), description: data.get('description'), limit: Number(data.get('limit')), joined: [], rewardGold: Number(data.get('rewardGold') || 0), rewardStats: Number(data.get('rewardStats') || 0), rewardItem: data.get('rewardItem'), image: questArt[Math.floor(Math.random() * questArt.length)], status: 'Open' }); log('admin', `Admin สร้างเควส ${data.get('title')}`); saveDb(); toast('อัปโหลดเควสขึ้นกระดานแล้ว'); render(); }
function settleQuest(qid, mid, complete) { const q = db.quests.find(x => x.id === qid); const m = db.members.find(x => x.id === mid); if (!q || !m) return; q.status = complete ? 'Completed' : 'Failed'; if (complete) { m.gold += q.rewardGold; m.availablePoints += q.rewardStats; if (q.rewardItem) m.inventory.push({ name: q.rewardItem, rarity: 'Quest Reward', description: `รางวัลจากภารกิจ ${q.title}`, image: '' }); m.completedQuests += 1; } log('admin', `Admin สรุปเควส ${q.title}: ${complete ? 'Complete' : 'Fail'} ให้ ${m.firstName}`); saveDb(); toast(complete ? 'มอบรางวัลภารกิจเรียบร้อย' : 'บันทึกภารกิจล้มเหลวแล้ว'); render(); }
function openItem(index) { const item = member()?.inventory[index]; if (!item) return; openModal(`<button class="close-modal" data-action="close-modal">×</button><div class="eyebrow">Inventory record</div><h2>${esc(item.name)}</h2><img src="${imageValue(item.image, itemArt[index % itemArt.length])}" alt="" style="width:100%;max-height:220px;object-fit:cover;border:1px solid var(--gold)"><p><span class="tag">${esc(item.rarity)}</span></p><p class="hint">${esc(item.description)}</p>`); }
function openAdminMember(id) { const m = db.members.find(x => x.id === id); if (!m) return; openModal(`<button class="close-modal" data-action="close-modal">×</button><div class="eyebrow">Member dossier</div><h2>${esc(m.firstName)} ${esc(m.lastName)}</h2><div class="meta-grid"><div><span>Age</span><strong>${m.age}</strong></div><div><span>Gender</span><strong>${esc(m.gender)}</strong></div><div><span>Gold</span><strong>${m.gold} ◈</strong></div><div><span>Class</span><strong>${esc(m.job)}</strong></div><div><span>Guild</span><strong>${esc(m.guild)}</strong></div><div><span>Rank</span><strong>${esc(m.rank)}</strong></div></div><button class="danger-btn" data-action="kick" data-id="${m.id}">เตะสมาชิก</button>`); }
function openModal(html) { document.querySelector('#modalContent').innerHTML = html; document.querySelector('#modalBackdrop').hidden = false; document.querySelectorAll('#modalContent [data-action]').forEach(btn => btn.addEventListener('click', handleAction)); }
function closeModal() { document.querySelector('#modalBackdrop').hidden = true; }
document.querySelector('#modalBackdrop').addEventListener('click', e => { if (e.target.id === 'modalBackdrop') closeModal(); });
render();
hydrateFromCloud();
setInterval(() => {
  if (document.visibilityState === 'visible') hydrateFromCloud();
}, 5000);
